aldoestebanpaz/rc-fullstack-8d-final-restorant

backend/package-lock.json
backend/package.json

Lo unico que hice fue correr npm install express

instalar express

---

backend/controllers/create.orders.js
backend/controllers/delete.orders.js
backend/controllers/reader.orders.js
backend/controllers/update.orders.js
backend/dataBase.js
backend/index.js
backend/models/orders.model.js
backend/routes/index.js
backend/routes/orders.routes.js

se crea el modelo - rutas - controllers - sea hace operaciones CRUD desde backend... funciona ok

se hace backend basico

---

frontend/src/App.js
frontend/src/config/.env.development
frontend/src/config/axios.js
frontend/src/pages/LoginSession.jsx
frontend/src/pages/RegUser.jsx

estuve creando la pagina de registro de usuario y la de inicio de sesion sin estilos y con campos por default, falta agregar mas campos

Page register user log sesión

---

frontend/package-lock.json
frontend/package.json
frontend/public/index.html
frontend/src/App.js
frontend/src/Css/Reguser.css
frontend/src/Css/logUser.css
frontend/src/pages/LoginSession.jsx
frontend/src/pages/RegUser.jsx
frontend/src/pages/Reguser.css

el reg y el log ya tienen sus estilos. Ya esta listo para darle funcionabilidad. Esta instalada la libreria sweetalert2.

Aplico estilos reg log

---

backend/controllers/foods/create.foods.js
backend/controllers/foods/readers.foods.js
backend/controllers/orden/reader.orden.js
backend/controllers/users/reader.users.js
backend/models/foods.model.js
backend/models/orden.model.js
backend/models/users.model.js
backend/routes/foods.routes.js
backend/routes/orden.routes.js
backend/routes/users.routes.js

se hace la conexion de schemas

Conexion schemas populate

---

backend/controllers/foods/create.foods.js
backend/controllers/foods/readers.foods.js
backend/controllers/orden/create.orden.js
backend/controllers/orden/read.orden.js
backend/controllers/orden/reader.orden.js
backend/controllers/users/delete.users.js
backend/controllers/users/read.users.js
backend/controllers/users/register.users.js
backend/routes/foods.routes.js
backend/routes/orden.routes.js
backend/routes/users.routes.js

se hace modificaciones a controllers y models

se hacen retoques en el codigo

---

backend/controllers/orden/reader.orden.js
backend/controllers/users/register.users.js

se hace modificaciones a controllers y models y populate

se hace las ultimas modificaciones de populate

---

backend/controllers/foods/create.foods.js
backend/controllers/orden/create.orden.js
backend/models/orden.model.js
backend/routes/orden.routes.js

se crea en el modelo de la orden el estado pendiente

se crea el estado pendiente en el back

---

backend/controllers/foods/create.foods.js
backend/controllers/orden/create.orden.js
backend/controllers/orden/read.orden.js
backend/controllers/orden/reader.orden.js
backend/models/orden.model.js
backend/models/users.model.js
backend/routes/orden.routes.js

se ajusta el modelo orden y las rutas de orden

ajustes en modal orden

---

backend/controllers/foods/create.foods.js
backend/controllers/foods/readSeveralAll.foods.js
backend/controllers/foods/readSeveralTrue.foods.js
backend/models/foods.model.js
backend/routes/foods.routes.js

se crea la propiedad enable en el modelo foods para poder crear la ruta que le corresponde a la comida que este en true... y se crean rutas para traer todas las cards de comidas sean true o false y se crea la ruta espesifica para true

se crea el enable en model food

---

backend/controllers/order/cancel.order.js
backend/controllers/order/readOne.order.js
backend/controllers/order/send.order.js
backend/controllers/order/update.order.js
backend/middlewares/authorize.js
backend/routes/order.routes.js

se crea las rutas para al tomar el pedido se cambie el estado a en proceso... y al enviar o al cancelar cambie el estado segun corresponda

se crean las rutas en proceso enviado cancelar para las ordenes

---

backend/controllers/foods/platend.foods.js
backend/routes/foods.routes.js

se crea la ruta del boolean false para food model

se crea la ruta del boolean false para food model

---

backend/controllers/foods/plateDis.foods.js
backend/routes/foods.routes.js

se crea el food true

---

frontend/public/index.html
frontend/src/App.js
frontend/src/components/Footer.jsx
frontend/src/pages/LoginSession.jsx
frontend/src/pages/Menu.jsx

listado de menu listo para agregar estilos

Listado de platos terminado sin estilos

---

backend/controllers/foods/admin/create.foods.js
backend/controllers/foods/admin/delete.foods.js
backend/controllers/foods/admin/plateDis.foods.js
backend/controllers/foods/admin/platend.foods.js
backend/controllers/foods/admin/readOne.foods.js
backend/controllers/foods/admin/readSeveralAll.foods.js
backend/controllers/foods/admin/update.foods.js
backend/controllers/foods/user/readSeveralTrue.foods.js
backend/controllers/order/admin/delete.order.js
backend/controllers/order/admin/readOne.order.js
backend/controllers/order/admin/readSeveral.order.js
backend/controllers/order/admin/send.order.js
backend/controllers/order/admin/update.order.js
backend/controllers/order/user/cancel.order.js
backend/controllers/order/user/create.order.js
backend/controllers/users/admin/delete.users.js
backend/controllers/users/admin/readOne.user.js
backend/controllers/users/admin/readSeveral.user.js
backend/controllers/users/user/login.users.js
backend/controllers/users/user/logout.users.js
backend/controllers/users/user/register.users.js
backend/models/order.model.js
backend/routes/foods.routes.js
backend/routes/order.routes.js
backend/routes/users.routes.js

se crean carpetas para dividir lo que hace el admin y el user

se crean carpetas para dividir lo que hace el admin y el user

---

backend/controllers/foods/createFoods.js
backend/controllers/foods/deleteFoods.js
backend/controllers/foods/plateDisFoods.js
backend/controllers/foods/platendFoods.js
backend/controllers/foods/readOneFoods.js
backend/controllers/foods/readSeveralAllFoods.js
backend/controllers/foods/readSeveralTrueFoods.js
backend/controllers/foods/updateFoods.js
backend/controllers/order/cancelOrder.js
backend/controllers/order/createOrder.js
backend/controllers/order/deleteOrder.js
backend/controllers/order/readOneOrder.js
backend/controllers/order/readSeveralOrder.js
backend/controllers/order/searchOrderUser.js
backend/controllers/order/sendOrder.js
backend/controllers/order/updateOrder.js
backend/controllers/users/deleteUsers.js
backend/controllers/users/loginUsers.js
backend/controllers/users/logoutUsers.js
backend/controllers/users/readOneUser.js
backend/controllers/users/readSeveralUser.js
backend/controllers/users/registerUsers.js
backend/middlewares/authorize.js
backend/models/order.model.js
backend/routes/foods.routes.js
backend/routes/order.routes.js
backend/routes/users.routes.js

se cambian los nombres de funciones controller a camelCase y se crea la ruta para que el usuario vea las ordenes

se hacen los ajustes vistos en clases martes 23/06

---

backend/controllers/order/readSeveralOrder.js
backend/controllers/order/searchOrderUser.js
backend/middlewares/authorize.js
backend/routes/foods.routes.js
backend/routes/order.routes.js
backend/routes/users.routes.js

se coloca el user y admin en las rutas users foods order

se coloca el user y admin en las rutas users foods order

---

backend/controllers/users/registerUsers.js
backend/models/users.model.js
backend/routes/users.routes.js

se crea en el modelo user el celular

se hace cambios en el modelo user

---

frontend/package.json
frontend/src/pages/LoginSession.jsx
frontend/src/pages/RegUser.jsx

se hacen cambios en el back y front

---

backend/controllers/foods/availableFoods.js
backend/controllers/foods/createFoods.js
backend/controllers/foods/deleteFoods.js
backend/controllers/foods/notAvailableFoods.js
backend/controllers/foods/readOneFoods.js
backend/controllers/foods/readSeveralAllFoods.js
backend/controllers/foods/readSeveralTrueFoods.js
backend/controllers/foods/updateFoods.js
backend/package-lock.json
backend/routes/foods.routes.js

se hace cambios en los controladores y rutas de plate a foods

se hace cambio de plate a foods

---

backend/index.js
frontend/src/pages/LoginSession.jsx
frontend/src/pages/RegUser.jsx

se agrega cors en el back y en el front se cambia number por phonenumber en el name del reguser

Agregando cors name

---

backend/controllers/order/searchOrderUser.js
backend/index.js
backend/routes/order.routes.js

se hace ajuste en la busqueda de las ordenes para user y admin..

se hace ajuste en la busqueda de las ordenes para user y admin

---

frontend/src/App.js
frontend/src/components/Header.jsx
frontend/src/components/PrivateRoute.jsx
frontend/src/index.js
frontend/src/pages/Menu.jsx
frontend/src/utils/auth.js

tarea realizada : crear una ruta privada para el admin que muestre todos los platos

trabajando sobre listados de todos los platos

---

backend/controllers/order/completedOrder.js
backend/controllers/order/processOrder.js
backend/controllers/order/readOneOrder.js
backend/controllers/order/readSeveralOrder.js
backend/controllers/order/searchOrderUser.js
backend/routes/order.routes.js

se hacen ajustes en la ruta order se crea la ruta para poner en proceso una order con PUT y no GET... se crea la ruta para la order en estado: finalizado.- y se actualiza el GET del usuario para que solo vea las ordenes en estado: enviado

se hace ajustes vistos en clases 30/06

---

backend/controllers/foods/createFoods.js
backend/controllers/foods/uploadImagesFoods.js
backend/controllers/order/cancelOrder.js
backend/controllers/order/completedOrder.js
backend/controllers/order/createOrder.js
backend/controllers/order/readOneOrder.js
backend/controllers/order/readSeveralOrder.js
backend/controllers/order/scoreOrder.js
backend/controllers/order/searchOrderUser.js
backend/controllers/order/sendOrder.js
backend/controllers/users/registerUsers.js
backend/middlewares/authorize.js
backend/models/foods.model.js
backend/models/order.model.js
backend/routes/order.routes.js

se modifica la ruta para hacer dinamico la direccion del user/admin en order y se crea la ruta para puntaje de order

direccion user order y ruta para puntaje de orden

---

backend/controllers/users/readOneUser.js
backend/controllers/users/readSeveralUser.js
backend/routes/foods.routes.js
backend/routes/order.routes.js
backend/routes/users.routes.js

detalles en las rutas order no estaban cuales eran user y cuales eran admin

detalles en las rutas

---

backend/controllers/order/cancelOrder.js
backend/controllers/order/completedOrder.js
backend/controllers/order/processOrder.js
backend/controllers/order/scoreOrder.js
backend/controllers/order/sendOrder.js
backend/controllers/users/readSeveralUser.js
backend/models/order.model.js
backend/models/users.model.js
backend/routes/order.routes.js

se hace refactoreo de codigo aumentando  algunas validaciones a las ordenes

se hace refactoreo de codigo

---

backend/controllers/order/searchOrderUser.js
backend/middlewares/authorize.js

se borran los states de los GEts

se borran los states de los GEts

---

frontend/src/components/Header.jsx
frontend/src/pages/EditFoods.jsx
frontend/src/pages/GetOrderPages.jsx
frontend/src/pages/GetOrderUserPages.jsx
frontend/src/pages/PlatoPage.jsx

modal de confirmacion en admin

se crea modal de confirmacion

---

frontend/src/components/MenuAdm.jsx

agregando detalles a las rutas

agregando rutas al menu adm

---

frontend/src/components/Header.jsx
frontend/src/components/MenuAdm.jsx
frontend/src/components/ModalLogin.jsx
frontend/src/pages/HomePage.jsx

ultimando detalles parte 10000

---

frontend/src/Css/CreateFoodsPage.css
frontend/src/Css/logUser.css
frontend/src/pages/AdmMenu.jsx
frontend/src/pages/CreateFoodsPage.jsx
frontend/src/pages/EditFoods.jsx
frontend/src/pages/GetOrderPages.jsx
frontend/src/pages/GetOrderUserPages.jsx

agregando cambios de andres

---

frontend/package-lock.json
frontend/src/Css/homepage.css
frontend/src/components/Header.jsx
frontend/src/components/SobreNosotros.jsx

agregue un modal con leyenda sobre nosotros y agregue unos estilos para que se vea mejor la card comida del menu principal

Modal sobre nosotros
